import HHTCoefficientCone
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.RuleOfSigns
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Data.Real.StarOrdered
import Lean.Elab.Tactic.Omega
import Mathlib.Tactic.FieldSimp

/-
Finite algebra only. The actual-xi root identification and spectral identities
are external inputs, not introduced as global propositions. The runner compiles
and audits the local coefficient dependency before compiling this file.
-/
set_option autoImplicit false
open scoped BigOperators
open HHTCoefficientCone
namespace HHTDeflation

noncomputable def ev {n : ℕ} (e : Fin n → ℕ) (a : Fin n → ℝ) (x : ℝ) : ℝ :=
  ∑ i, a i * x ^ e i

noncomputable def cp {n : ℕ} (e : Fin n → ℕ) (a : Fin n → ℝ) : Polynomial ℝ :=
  ∑ i, Polynomial.C (a i) * Polynomial.X ^ e i

noncomputable def rect {n : ℕ} (e : Fin n → ℕ) (a b : Fin n → ℝ)
    (c l R : ℝ) : ℝ :=
  boxSq c (ev e b l) (ev e b R) +
  boxSq (ev e b R-c) (ev e a l) (ev e a R) - (ev e b R-c)^2

/-- Nonnegative coefficients evaluated at a nonnegative point stay nonnegative. -/
theorem coefficient_eval_nonneg {n : ℕ} (e : Fin n → ℕ) (a : Fin n → ℝ)
    (ha : ∀ i, 0 ≤ a i) (x : ℝ) (hx : 0 ≤ x) : 0 ≤ ev e a x := by
  unfold ev
  exact Finset.sum_nonneg (fun i _ => mul_nonneg (ha i) (pow_nonneg hx _))

/-- Evaluation is monotone in a nonnegative argument, without a degree bound. -/
theorem coefficient_eval_mono {n : ℕ} (e : Fin n → ℕ) (a : Fin n → ℝ)
    (ha : ∀ i, 0 ≤ a i) (x y : ℝ) (hx : 0 ≤ x) (hxy : x ≤ y) :
    ev e a x ≤ ev e a y := by
  unfold ev
  exact Finset.sum_le_sum (fun i _ =>
    mul_le_mul_of_nonneg_left (pow_le_pow_left₀ hx hxy (e i)) (ha i))

/-- The finite coefficient evaluation is evaluation of an actual polynomial. -/
theorem coefficient_polynomial_eval {n : ℕ} (e : Fin n → ℕ)
    (a : Fin n → ℝ) (x : ℝ) : (cp e a).eval x = ev e a x := by
  unfold cp ev
  rw [Polynomial.eval_finsetSum]
  apply Finset.sum_congr rfl
  intro i _
  simp

/-- The rectangular lower certificate cannot exceed a pointwise polynomial square. -/
theorem rectangle_point_upper (c u v ua ub va vb : ℝ)
    (hu : 0 ≤ u) (hu0 : ua ≤ u) (hu1 : u ≤ ub)
    (hv0 : va ≤ v) (hv1 : v ≤ vb) :
    boxSq c va vb + boxSq (vb-c) ua ub - (vb-c)^2 ≤ (c+u-v)^2 := by
  have h1 := box_square_lower c va vb v hv0 hv1
  have h2 := box_square_lower (vb-c) ua ub u hu0 hu1
  have h3 : 0 ≤ u*(vb-v) := mul_nonneg hu (sub_nonneg.mpr hv1)
  nlinarith

/-- A root in the ratio interval blocks a strictly positive rectangle certificate. -/
theorem coefficient_root_barrier {n : ℕ} (e : Fin n → ℕ) (a b : Fin n → ℝ)
    (c l R x : ℝ) (ha : ∀ i, 0 ≤ a i) (hb : ∀ i, 0 ≤ b i)
    (hl : 0 ≤ l) (hlx : l ≤ x) (hxR : x ≤ R)
    (hroot : c+ev e a x-ev e b x=0) : rect e a b c l R ≤ 0 := by
  have hx : 0 ≤ x := le_trans hl hlx
  have hu := coefficient_eval_nonneg e a ha x hx
  have hua := coefficient_eval_mono e a ha l x hl hlx
  have hub := coefficient_eval_mono e a ha x R hx hxR
  have hva := coefficient_eval_mono e b hb l x hl hlx
  have hvb := coefficient_eval_mono e b hb x R hx hxR
  have h := rectangle_point_upper c (ev e a x) (ev e b x)
    (ev e a l) (ev e a R) (ev e b l) (ev e b R) hu hua hub hva hvb
  simpa [rect, hroot] using h

/-- This is algebraic polynomial division, not an assumed orthogonal projection. -/
theorem polynomial_decomposition (p A : Polynomial ℝ) :
    p = p %ₘ A + A * (p /ₘ A) :=
  (Polynomial.modByMonic_add_div p A).symm

noncomputable def ann : List ℝ → Polynomial ℝ
  | [] => 1
  | x :: xs => (Polynomial.X - Polynomial.C x) * ann xs

/-- Every listed anchor is killed exactly. -/
theorem ann_eval_zero (xs : List ℝ) (x : ℝ) (hx : x ∈ xs) :
    (ann xs).eval x = 0 := by
  induction xs with
  | nil => simp at hx
  | cons a xs ih =>
    rcases List.mem_cons.mp hx with h | h
    · subst a
      simp [ann]
    · simp [ann, ih h]

/-- The annihilating product is not the zero polynomial. -/
theorem ann_ne_zero (xs : List ℝ) : ann xs ≠ 0 := by
  induction xs with
  | nil => simp [ann]
  | cons a xs ih =>
    exact mul_ne_zero (Polynomial.X_sub_C_ne_zero a) ih

/-- Each positive anchor factor adds a sign variation, including multiplicities. -/
theorem ann_sign_variations (xs : List ℝ) (q : Polynomial ℝ)
    (hq : q ≠ 0) (hpos : ∀ x ∈ xs, 0 < x) :
    xs.length + q.signVariations ≤ (ann xs*q).signVariations := by
  induction xs with
  | nil => simp [ann]
  | cons a xs ih =>
    have hxs : ∀ x ∈ xs, 0 < x := fun x hx => hpos x (List.mem_cons_of_mem a hx)
    have htail := ih hxs
    have hprod : ann xs*q ≠ 0 := mul_ne_zero (ann_ne_zero xs) hq
    have hstep := Polynomial.succ_signVariations_le_X_sub_C_mul
      (hpos a (List.mem_cons_self)) hprod
    simp only [ann, mul_assoc, List.length_cons] at *
    omega

/-- The whole ideal generated by the annihilator is in the evaluation kernel. -/
theorem ann_product_eval_zero (xs : List ℝ) (q : Polynomial ℝ)
    (x : ℝ) (hx : x ∈ xs) : (ann xs*q).eval x = 0 := by
  simp [Polynomial.eval_mul, ann_eval_zero xs x hx]

/-- Actual polynomial coordinates connect the interval barrier to the entire ideal. -/
theorem annihilator_coefficient_barrier {n : ℕ} (e : Fin n → ℕ)
    (a b : Fin n → ℝ) (c l R x : ℝ) (xs : List ℝ) (q : Polynomial ℝ)
    (ha : ∀ i, 0 ≤ a i) (hb : ∀ i, 0 ≤ b i)
    (hl : 0 ≤ l) (hlx : l ≤ x) (hxR : x ≤ R) (hx : x ∈ xs)
    (hpoly : Polynomial.C c + cp e a - cp e b = ann xs*q) :
    rect e a b c l R ≤ 0 := by
  apply coefficient_root_barrier e a b c l R x ha hb hl hlx hxR
  have heq := congrArg (fun p : Polynomial ℝ => p.eval x) hpoly
  simpa [Polynomial.eval_add, Polynomial.eval_sub, coefficient_polynomial_eval,
    Polynomial.eval_C, ann_product_eval_zero xs q x hx] using heq

/-- The known finite spectral quadratic form is exactly zero on this ideal. -/
theorem prefix_quadratic_zero {N : ℕ} (xs : List ℝ) (q : Polynomial ℝ)
    (u w : Fin N → ℝ) (k : ℕ) (hu : ∀ i, u i ∈ xs) :
    (∑ i, w i * (u i)^(k+1) * ((ann xs*q).eval (u i))^2) = 0 := by
  apply Finset.sum_eq_zero
  intro i _
  simp [ann_product_eval_zero xs q (u i) (hu i)]

/-- The correct missing block is the Schur complement, with real Matrix.PosSemidef. -/
theorem schur_psd_iff {N M : ℕ} (C : Matrix (Fin N) (Fin N) ℝ)
    (E : Matrix (Fin N) (Fin M) ℝ) (D : Matrix (Fin M) (Fin M) ℝ)
    (hC : C.PosDef) :
    (Matrix.fromBlocks C E E.conjTranspose D).PosSemidef ↔
      (D-E.conjTranspose*C⁻¹*E).PosSemidef := by
  let _ : Invertible C := hC.isUnit.invertible
  exact Matrix.PosDef.fromBlocks₁₁ E D hC

/-- Scalar square completion records the mixed-term penalty explicitly. -/
theorem schur_scalar_identity (C E D r q : ℝ) (hC : C ≠ 0) :
    C*r^2+2*E*r*q+D*q^2 = C*(r+E/C*q)^2+(D-E^2/C)*q^2 := by
  field_simp [hC]
  ring

#print axioms HHTDeflation.coefficient_eval_nonneg
#print axioms HHTDeflation.coefficient_eval_mono
#print axioms HHTDeflation.coefficient_polynomial_eval
#print axioms HHTDeflation.rectangle_point_upper
#print axioms HHTDeflation.coefficient_root_barrier
#print axioms HHTDeflation.polynomial_decomposition
#print axioms HHTDeflation.ann_eval_zero
#print axioms HHTDeflation.ann_ne_zero
#print axioms HHTDeflation.ann_sign_variations
#print axioms HHTDeflation.ann_product_eval_zero
#print axioms HHTDeflation.annihilator_coefficient_barrier
#print axioms HHTDeflation.prefix_quadratic_zero
#print axioms HHTDeflation.schur_psd_iff
#print axioms HHTDeflation.schur_scalar_identity

end HHTDeflation
